### ISSUE TITLE
Can you Convert Model into ONNX ? 

### ISSUE THREAD

**Issue by AMEERAZAM08** [WindVChen/INR-Harmonization#4]
I was working on to convert onnx but getting too many error , @WindVChen 
If possible you can define reference input  and output model params because i have seen the model taking list for all image,mask,fg_coordinates but this are  depent on image size so possible if will change the split_num then we will get something else input size for fg_coordinates, but you mention for loop for to get all var from datasets class that is taking the all image in dict formats having images in array .
My issue is that while taking all of static list all composite ,mask,fg_coordniate,all are in list of size 4 and having tensor with [B,C,W,H].
if possible can you help me out

**Comment by WindVChen** [comment]
Hi @AMEERAZAM08 ,

I appreciate your efforts to convert the model into ONNX, but I'm having some difficulty understanding your specific issue.

It seems like you are encountering errors while working on the conversion. However, I am unclear about the exact problem you are facing and the context of your request. Could you please provide more specific details about the errors you are encountering or the specific help you need?

**Comment by AMEERAZAM08** [comment]
This is code that I'm using to convert into onnx. but getting error related the input params model
```
composite_image_dummy = torch.randn(4, 3, 256, 256).to('cuda')
mask_dummy = torch.randn(4, 1, 256, 256).to('cuda')
fg_inr_coordinates_dummy = torch.randn(4, 2, 284, 284).to('cuda')
dynamic_axes = {
    'composite_image': {0: 'batch_size', 2: 'height', 3: 'width'},
    'mask': {0: 'batch_size', 2: 'height', 3: 'width'},
    'fg_inr_coordinates': {0: 'batch_size', 2: 'height', 3: 'width'}
}

torch.onnx.export(model, 
                  (composite_image_dummy, mask_dummy, fg_inr_coordinates_dummy), 
                  "model.onnx", 
                  export_params=True, 
                  opset_version=12, 
                  do_constant_folding=True, 
                  input_names=['composite_image', 'mask', 'fg_inr_coordinates'], 
                  output_names=['output'],
                  dynamic_axes=dynamic_axes)
```

**Comment by AMEERAZAM08** [comment]
@WindVChen ?

**Comment by WindVChen** [comment]
Hi @AMEERAZAM08 ,

I've experimented with the code you shared and made some minor adjustments:
```python
composite_image_dummy = torch.randn(1, 3, 256, 256).to('cuda')
mask_dummy = torch.randn(1, 1, 256, 256).to('cuda')
fg_inr_coordinates_dummy = torch.randn(1, 1, 2).to('cuda')
dynamic_axes = {
    'composite_image': {0: 'batch_size', 2: 'height', 3: 'width'},
    'mask': {0: 'batch_size', 2: 'height', 3: 'width'},
    'fg_inr_coordinates': {0: 'batch_size', 1: 'res'}
}

torch.onnx.export(model,
                  (composite_image_dummy, mask_dummy, fg_inr_coordinates_dummy),
                  "model.onnx",
                  export_params=True,
                  opset_version=16,
                  do_constant_folding=True,
                  input_names=['composite_image', 'mask', 'fg_inr_coordinates'],
                  output_names=['output'],
                  dynamic_axes=dynamic_axes)
```

And the error I encountered is: ``RuntimeError: Unsupported: ONNX export of operator Unfold, input size not accessible. Please feel free to reguest support or submit a poll request on Pytorch GitHub.``

It appears that the issue stems from the lack of ONNX support for the **Tensor.unfold** operation. To address this issue, I suggest opening an issue under the PyTorch/ONNX repositories to bring attention to this unsupported operation. This might pave the way for potential solutions.

Best regards.

**Comment by AMEERAZAM08** [comment]
Yes but issue it that onnx haven't resolve this erro till. 
Sure i will do this
